version: "3.9"

services:
  web:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - source_data:/var/www/html
    depends_on:
      - php
    networks:
      - app-network
      
  rabbitmq:
    image: rabbitmq:3.9.7-management
    restart: always
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - app-network
      
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network

  php:
    build:
      args:
        NEW_RELIC_KEY: ${NEW_RELIC_KEY}
      context: .
      dockerfile: php/Dockerfile.prod
    restart: always
    ports:
      - 9000
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - source_data:/var/www/html
    depends_on:
      - database
      - rabbitmq
      - redis
    networks:
      - app-network

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - 8191
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  database_data:
  rabbitmq_data:
  redis_data:

networks:
  app-network:
    driver: bridge
