# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true
        
        bind:
            $OPENAI_API_KEY: 'fgdfgdfg'

    Symfony\Component\HttpClient\MockHttpClient: ~
    
    Symfony\Contracts\HttpClient\HttpClientInterface:
        alias:  Symfony\Component\HttpClient\MockHttpClient
        public: true
    
    Orhanerday\OpenAi\OpenAi: ~
    PHPHtmlParser\Dom: ~
    
    _instanceof:
        App\Service\ContextProvider\ContextProviderInterface:
            tags: ['app.provider.news']
            
        App\Service\Parser\SiteParserInterface:
             tags: ['app.parser.site']
             
        App\Service\Spread\SpreadProviderInterface:
             tags: ['app.spread.provider']
            
    App\MessageHandler\ContextHandler:
        arguments:
            $contextProviders: !tagged_iterator app.provider.news
            
    App\Service\Parser\ParserFactory:
        arguments:
            $siteParsers: !tagged_iterator app.parser.site
            
    App\Service\Spread\SpreadProviderFactory:
        arguments:
            $spreadProviders: !tagged_iterator app.spread.provider
